BASE    {{ldap_base_dn}}
URI     ldap://{{ldap_host}}

BINDDN {{ldap_bind_dn}}
BINDPW {{ldap_bind_password}}

sudoers_base {{ldap_base_dn}}

SUDOERS_SEARCH_FILTER (|(memberof=cn=host_admin,ou=Groups,{{ldap_base_dn}})(memberof=cn=host_{{current_host}}_admin,ou=Groups,{{ldap_base_dn}}))
