BASE    {{ldap_base_dn}}
URI     ldap://{{ldap_host}}

BINDDN {{ldap_bind_dn}}
BINDPW {{ldap_bind_password}}

sudoers_base {{ldap_base_dn}}

SUDOERS_SEARCH_FILTER (|{{#ldap_sudo_groups}}(memberof={{.}},ou=Groups,{{ldap_base_dn}}){{/ldap_sudo_groups}})
